endpoint: vpn.example.com
gw_iface: eth0
wg_bin: wg
wg_quick_bin: wg-quick
iptables_bin: iptables
interfaces:
  scranton_vpn:
    name: scranton_vpn
    description: VPN for Scranton branch
    ipv4_address: 10.0.100.1/24
    listen_port: 56377
    private_key: cAQ9ij0rdWUWFjAXzRQJj69cUYZmxu5h9QQnEIkcJFQ=
    public_key: SMHYP2ZIFOWXyB1X9zeeNZkSLPmwWRp65uTrDbCDIkA=
    on_up:
    - iptables -I FORWARD -i scranton_vpn -j ACCEPT
    - iptables -I FORWARD -o scranton_vpn -j ACCEPT
    - iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE
    on_down:
    - iptables -D FORWARD -i scranton_vpn -j ACCEPT
    - iptables -D FORWARD -o scranton_vpn -j ACCEPT
    - iptables -D nat -I POSTROUTING -o eth0 -j MASQUERADE
clients:
  jim:
    name: jim
    description: ''
    ipv4_address: 10.0.100.2/24
    private_key: MGv+gZb5OFMFyfRyaooRK2wk4NvPqKwrO1LV6PfamWY=
    public_key: qpsBq/+pK+HZQPp+Mv6g8paoE0bjgzYubJUf+bIJ42o=
    nat: false
    interface: scranton-vpn
    dns1: 8.8.8.8
    dns2: null
