logger:
  level: info
  logfile: /var/www/linguard/linguard.log
  overwrite: no

web:
  bindport: 8000
  login_attempts: 10

linguard:
  endpoint: vpn.example.com
  gw_iface: eth0
  wg_bin: /usr/bin/wg
  wg_quick_bin: /usr/bin/wg-quick
  iptables_bin: /usr/sbin/iptables
  interfaces_folder: /var/www/linguard/interfaces
  interfaces:
    9e11e7305c9b4878a1f2a17aab67828d:
      uuid: 9e11e7305c9b4878a1f2a17aab67828d
      name: scranton-vpn
      description: 'vpn for scranton branch'
      gw_iface: eth0
      ipv4_address: 10.200.51.226/28
      listen_port: 60726
      private_key: OJ7La8nuZ1TuuhcZ+Xf5i2q1ZrFXQNmKmu/toYiPmlU=
      public_key: 9kBWGjY8XHDHjbxhJmwBhR+uJ2Alxl/SI1gUXoRGOCM=
      auto: false
      on_up:
        - /usr/sbin/iptables -I FORWARD -i scranton-vpn -j ACCEPT
        - /usr/sbin/iptables -I FORWARD -o scranton-vpn -j ACCEPT
        - /usr/sbin/iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE
      on_down:
        - /usr/sbin/iptables -D FORWARD -i scranton-vpn -j ACCEPT
        - /usr/sbin/iptables -D FORWARD -o scranton-vpn -j ACCEPT
        - /usr/sbin/iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      peers:
        35c026b40a8a4c8d92f8668006905c5a:
          uuid: 35c026b40a8a4c8d92f8668006905c5a
          name: Jim Halpert
          description: ''
          ipv4_address: 10.200.51.227/28
          private_key: yCAiQuYDUxjyzrCP7BwbE2UgqV5L6d+YlaxretwtvlI=
          public_key: YmuZlDpuJed8uV9BkjHuzBKZTlAhdoqPKwgNtEWDdU4=
          endpoint: vpn.example.com:60726
          nat: false
          dns1: 8.8.8.8
          dns2: 8.8.4.4
