linguard: !yamlable/linguard
  endpoint: vpn.example.com
  interfaces: !yamlable/interfaces
    39a855187c4c4ca694d8c3f215e76cdc: !yamlable/interface
      auto: false
      description: 'vpn for scranton branch'
      gw_iface: enp0s31f6
      ipv4_address: 192.168.92.234/21
      listen_port: '52123'
      name: scranton-vpn
      on_down:
      - /usr/sbin/iptables -D FORWARD -i tough-moth -j ACCEPT
      - /usr/sbin/iptables -D FORWARD -o tough-moth -j ACCEPT
      - /usr/sbin/iptables -t nat -D POSTROUTING -o enp0s31f6 -j MASQUERADE
      on_up:
      - /usr/sbin/iptables -I FORWARD -i tough-moth -j ACCEPT
      - /usr/sbin/iptables -I FORWARD -o tough-moth -j ACCEPT
      - /usr/sbin/iptables -t nat -I POSTROUTING -o enp0s31f6 -j MASQUERADE
      peers: {}
      private_key: 4Ob32NhyhwIXbj7od6L5ASWle3vbOjn9g80at/dxPm0=
      public_key: 7NTAVIucHQJsS9Z8eT3lUV8VUoTSFrB6J272F9ox5RQ=
      uuid: 39a855187c4c4ca694d8c3f215e76cdc
  interfaces_folder: /var/www/linguard/interfaces
  iptables_bin: /usr/sbin/iptables
  wg_bin: /usr/bin/wg
  wg_quick_bin: /usr/bin/wg-quick
logger: !yamlable/logger
  level: debug
  logfile: /var/www/linguard/linguard.log
  overwrite: false
web: !yamlable/web
  bindport: 8080
  credentials_file: /var/www/linguard/credentials.yaml
  login_attempts: 0
  secret_key: G,XhSEIu{>TFu$y?4-kMy+<MN%T*J@/[
