uwsgi:
  master: true
  enable-threads: true
  chdir: /var/www/linguard
  venv: venv
  wsgi-file: linguard/__main__.py
  pyargv: config/linguard.sample.yaml
  need-plugin: python3
  callable: app
  die-on-term: true
  http-socket: 0.0.0.0:8080
  chmod-socket: 660
  vacuum: true