name: git-install

on:
  push:
    branches:
      - main
    paths:
      - "**/install.sh"
      - "**/git-install.yaml"
      - "**/uwsgi-sample.yaml"

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
    - name: Download and install
      run: |
        wget -q https://raw.githubusercontent.com/joseantmazonsb/linguard/main/scripts/install.sh
        chmod +x install.sh
        sudo ./install.sh /var/www/linguard

    - name: Briefly test using uWSGI
      run: |
        sudo -u linguard uwsgi --yaml /var/www/linguard/config/uwsgi.sample.yaml &
        sleep 2s
        sudo pkill -f uwsgi