on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: |
          - echo "::set-output name=version::$(cat pyproject.toml | grep version | xargs | cut -d ' ' -f 3)"
      - name: Build artifacts
        run: |
          - ./build.sh
      - name: Create GH release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.get_version.outputs.version }}
          tag: "v${{ steps.get_version.outputs.version }}"
          commit: "main"
          artifacts: "dist/*.tar.gz"
          bodyFile: "release-notes.md"
          discussionCategory: "Announcements"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stable
          platforms: "linux/amd64, linux/arm64"
          push: true